codecov:
  require_ci_to_pass: true

ignore:
  - ".guardrails/**"
  - ".deepsource.toml"
  - ".qlty/**"
  - ".github/dependabot.yml"

coverage:
  precision: 2
  round: down
  range: "100...100"
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"

bundle_analysis:
  warning_threshold: "0%"
  status: informational
